alter table public.templates
  add column if not exists description text,
  add column if not exists cover_url text,
  add column if not exists preview_video_url text,
  add column if not exists source_video_url text,
  add column if not exists generation_mode text not null default 'legacy',
  add column if not exists required_photo_count integer not null default 1,
  add column if not exists photo_rules jsonb not null default '[]'::jsonb,
  add column if not exists available_resolutions jsonb not null default '["720p"]'::jsonb;

insert into public.templates (
  slug,
  title,
  description,
  video_prompt,
  photo_prompt,
  price_rub,
  is_active,
  cover_url,
  preview_video_url,
  source_video_url,
  generation_mode,
  required_photo_count,
  photo_rules,
  available_resolutions,
  photo_model,
  video_model,
  aspect_ratio,
  duration,
  resolution
) values (
  'popstar',
  'Попстар',
  'Станьте главным героем звёздной вечеринки.',
  'Replace only the main performer with the person from image 1 and the security guard with the person from image 2. Keep image 1 and image 2 as two separate, stable identities throughout the video. Keep every other person unchanged. Preserve the original camera movement, cuts, timing, actions, facial expressions, clothing, props, lighting, locations, background, and audio. At 14 seconds, preserve the original phone handoff from the performer to the security guard. Do not add, remove, merge, or duplicate people. Photorealistic live-action.',
  '',
  1,
  true,
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-cover.jpg',
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-preview.mp4',
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-source.mp4',
  'genjutsu_motion_template',
  2,
  '["Исполнитель", "Охранник"]'::jsonb,
  '["480p", "720p", "1080p"]'::jsonb,
  'none',
  'genjutsu_motion',
  '16:9',
  29,
  '480p'
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  video_prompt = excluded.video_prompt,
  photo_prompt = excluded.photo_prompt,
  price_rub = excluded.price_rub,
  is_active = excluded.is_active,
  cover_url = excluded.cover_url,
  preview_video_url = excluded.preview_video_url,
  source_video_url = excluded.source_video_url,
  generation_mode = excluded.generation_mode,
  required_photo_count = excluded.required_photo_count,
  photo_rules = excluded.photo_rules,
  available_resolutions = excluded.available_resolutions,
  photo_model = excluded.photo_model,
  video_model = excluded.video_model,
  aspect_ratio = excluded.aspect_ratio,
  duration = excluded.duration,
  resolution = excluded.resolution;
