alter table public.templates
  add column if not exists description text,
  add column if not exists cover_url text,
  add column if not exists preview_video_url text,
  add column if not exists source_video_url text,
  add column if not exists generation_mode text not null default 'legacy',
  add column if not exists required_photo_count integer not null default 1,
  add column if not exists photo_rules jsonb not null default '[]'::jsonb,
  add column if not exists available_resolutions jsonb not null default '["720p"]'::jsonb;

insert into public.templates (
  slug,
  title,
  description,
  video_prompt,
  photo_prompt,
  price_rub,
  is_active,
  cover_url,
  preview_video_url,
  source_video_url,
  generation_mode,
  required_photo_count,
  photo_rules,
  available_resolutions,
  photo_model,
  video_model,
  aspect_ratio,
  duration,
  resolution
) values (
  'popstar',
  'Попстар',
  'Станьте главным героем звёздной вечеринки.',
  $prompt$Edit the uploaded source video while preserving its complete original sequence. Image 1 replaces only the main performer in light clothing at the front of the scene. Lock the exact recognizable identity from image 1 in every shot: preserve the face shape, head shape, eyes, eyebrows, nose, lips, jawline, ears, skin tone, facial hair, hairline, hairstyle, age, height, weight, body build, shoulder width, and natural body proportions. Never blend image 1 with the original actor or with any other person. Map image 1 precisely onto the original performer's head position, eye line, facial expressions, mouth movement, gestures, walking, stair descent, poses, timing, and interaction with all props. Preserve the clothing, footwear, jewelry, glasses, and accessories shown in image 1 consistently throughout the video. The static four-panel pop-art portrait beside the stairs must depict the same person from image 1 in all four panels while preserving the original panel layout, colors, size, position, perspective, lighting, and occlusion. At approximately 15 seconds, preserve the original action in which the main performer hands the mobile phone directly into the security guard's hand. Show one continuous, physically natural handoff: keep the phone clearly visible as it leaves the performer's hand and enters the guard's hand, preserving the original hand positions, arm trajectories, timing, and contact. The phone must not disappear, duplicate, drop, remain in the performer's hand, or appear in the guard's hand before contact. Preserve the original camera movement, camera shake, framing, focus, cuts, duration, acting rhythm, villa interior, staircase, windows, lighting, party guests, background movement, props, shadows, and audio. Keep all unassigned people unchanged and moving naturally. Do not add, remove, merge, duplicate, or reposition people. Photorealistic live-action, stable identity, natural skin, no face morphing, no body-shape drift, no flicker, and no restyle. Image 2 replaces only the tall security guard dressed in black who follows the performer and appears behind him near the stairs. Lock the exact recognizable identity, face, hair, skin tone, age, height, weight, body build, and natural proportions from image 2 in every appearance. Preserve the clothing and accessories shown in image 2 consistently. Keep image 1 and image 2 as two completely separate identities: never swap, blend, merge, or average their facial or body features. Map image 2 only onto the original guard's position, posture, walking, gestures, timing, and interaction with the performer. Do not apply image 2 to the performer or any party guest.$prompt$,
  '',
  1,
  true,
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-cover.jpg',
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-preview.mp4',
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-source.mp4',
  'genjutsu_motion_template',
  2,
  '["Исполнитель", "Охранник"]'::jsonb,
  '["480p", "720p", "1080p"]'::jsonb,
  'none',
  'genjutsu_motion',
  '16:9',
  30,
  '480p'
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  video_prompt = excluded.video_prompt,
  photo_prompt = excluded.photo_prompt,
  price_rub = excluded.price_rub,
  is_active = excluded.is_active,
  cover_url = excluded.cover_url,
  preview_video_url = excluded.preview_video_url,
  source_video_url = excluded.source_video_url,
  generation_mode = excluded.generation_mode,
  required_photo_count = excluded.required_photo_count,
  photo_rules = excluded.photo_rules,
  available_resolutions = excluded.available_resolutions,
  photo_model = excluded.photo_model,
  video_model = excluded.video_model,
  aspect_ratio = excluded.aspect_ratio,
  duration = excluded.duration,
  resolution = excluded.resolution;
