alter table public.templates
  add column if not exists description text,
  add column if not exists cover_url text,
  add column if not exists preview_video_url text,
  add column if not exists source_video_url text,
  add column if not exists generation_mode text not null default 'legacy',
  add column if not exists required_photo_count integer not null default 1,
  add column if not exists photo_rules jsonb not null default '[]'::jsonb,
  add column if not exists available_resolutions jsonb not null default '["720p"]'::jsonb;

insert into public.templates (
  slug,
  title,
  description,
  video_prompt,
  photo_prompt,
  price_rub,
  is_active,
  cover_url,
  preview_video_url,
  source_video_url,
  generation_mode,
  required_photo_count,
  photo_rules,
  available_resolutions,
  photo_model,
  video_model,
  aspect_ratio,
  duration,
  resolution
) values (
  'popstar',
  'Попстар',
  'Станьте главным героем звёздной вечеринки.',
  $prompt$Edit the uploaded source video while preserving its complete original sequence. Image 1 replaces only the main performer in light clothing at the front of the scene. Lock the exact recognizable identity from image 1 in every shot: preserve the face shape, head shape, eyes, eyebrows, nose, lips, jawline, ears, skin tone, facial hair, hairline, hairstyle, age, height, weight, body build, shoulder width, and natural body proportions. Never blend image 1 with the original actor or with any other person. Map image 1 precisely onto the original performer's head position, eye line, facial expressions, gestures, walking, stair descent, poses, timing, and interaction with all props. The person from image 1 must reproduce the original performer's visible lip-sync frame by frame and phoneme by phoneme: preserve every mouth shape, lip opening and closing, jaw movement, cheek movement, expression transition, and exact timing. Copy the original visible mouth performance even when the source video has no audible track, and keep the lips synchronized with the original performance throughout every close-up and profile view. Preserve the clothing, footwear, jewelry, glasses, and accessories shown in image 1 consistently throughout the video. The static four-panel pop-art portrait beside the stairs must depict the same person from image 1 in all four panels while preserving the original panel layout, colors, size, position, perspective, lighting, and occlusion. At approximately 15 seconds, the person from image 1 must throw the mobile phone backward toward the security guard behind him. Preserve the original throwing gesture, backward arm motion, release point, phone rotation, airborne trajectory, distance, timing, and catch. Show one continuous, physically natural throw: the phone must clearly leave the performer's hand, travel visibly through the air behind him, and be caught by the security guard. The phone must not disappear, duplicate, drop, remain in the performer's hand, teleport, or appear in the guard's hand before the catch. Preserve the original camera movement, camera shake, framing, focus, cuts, duration, acting rhythm, villa interior, staircase, windows, lighting, party guests, background movement, props, shadows, and audio. Keep all unassigned people unchanged and moving naturally. Do not add, remove, merge, duplicate, or reposition people. Photorealistic live-action, stable identity, natural skin, no face morphing, no body-shape drift, no flicker, and no restyle. Image 2 must replace the existing original bald, bearded adult man wearing black who acts as the security guard and follows the performer on and below the stairs. Target this exact existing bald bearded man in every frame where he is visible, including distant, partial, side, and occluded views. Remove his original identity completely and map the person from image 2 onto the exact same body track, position, scale, depth, posture, walking, gestures, timing, and interaction with the performer. At approximately 15 seconds, the person from image 2 must catch the mobile phone thrown backward by the person from image 1, using the original guard's exact catching motion and timing. This is strictly a replacement of an existing person, never an insertion: do not add the person from image 2 behind the guard, beside the guard, elsewhere on the stairs, or anywhere else in the scene. The original bald bearded man must no longer remain visible after replacement, and the total number of people must remain exactly the same as in the source video. Lock the exact recognizable identity, face, hair, skin tone, age, height, weight, body build, and natural proportions from image 2 in every appearance. Preserve the clothing and accessories shown in image 2 consistently. Keep image 1 and image 2 as two completely separate identities: never swap, blend, merge, or average their facial or body features. Do not apply image 2 to the performer or any party guest. No duplicate guard, no extra person, and no new background character.$prompt$,
  '',
  346,
  true,
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-cover.jpg',
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-preview.mp4',
  'https://tg-miniapp-liart.vercel.app/assets/templates/popstar-source.mp4',
  'genjutsu_motion_template',
  2,
  '["Исполнитель", "Охранник"]'::jsonb,
  '["480p", "720p", "1080p"]'::jsonb,
  'none',
  'genjutsu_motion',
  '16:9',
  30,
  '480p'
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  video_prompt = excluded.video_prompt,
  photo_prompt = excluded.photo_prompt,
  price_rub = excluded.price_rub,
  is_active = excluded.is_active,
  cover_url = excluded.cover_url,
  preview_video_url = excluded.preview_video_url,
  source_video_url = excluded.source_video_url,
  generation_mode = excluded.generation_mode,
  required_photo_count = excluded.required_photo_count,
  photo_rules = excluded.photo_rules,
  available_resolutions = excluded.available_resolutions,
  photo_model = excluded.photo_model,
  video_model = excluded.video_model,
  aspect_ratio = excluded.aspect_ratio,
  duration = excluded.duration,
  resolution = excluded.resolution;
