alter table public.templates
  add column if not exists description text,
  add column if not exists cover_url text,
  add column if not exists preview_video_url text,
  add column if not exists source_video_url text,
  add column if not exists generation_mode text not null default 'legacy',
  add column if not exists required_photo_count integer not null default 1,
  add column if not exists photo_rules jsonb not null default '[]'::jsonb,
  add column if not exists available_resolutions jsonb not null default '["720p"]'::jsonb;

alter table public.orders
  add column if not exists template_options jsonb not null default '{}'::jsonb;

insert into public.templates (
  slug,
  title,
  description,
  video_prompt,
  photo_prompt,
  price_rub,
  is_active,
  cover_url,
  preview_video_url,
  source_video_url,
  generation_mode,
  required_photo_count,
  photo_rules,
  available_resolutions,
  photo_model,
  video_model,
  aspect_ratio,
  duration,
  resolution
) values (
  'rap_in_car',
  'Рэп в машине',
  'Замените четырёх героев ролика своими фотографиями.',
  'Replace exactly four source-video actors with four separate people from the reference images. Treat every reference image as an exclusive identity source. Never average, blend, merge, or borrow facial or body features between references, and never mix a reference identity with the original source actor. Strict mapping for the entire video: image 1 exclusively defines the front-left passenger (screen left foreground); image 2 exclusively defines the front-right driver behind the steering wheel (screen right foreground); image 3 exclusively defines the rear-left passenger (screen left background); image 4 exclusively defines the rear-right passenger (screen right background). Never swap these identities or positions. CRITICAL IDENTITY PRIORITY: the front-right driver must be an exact, recognizable reproduction of image 2 only. Copy image 2''s face geometry, head shape, eyes, eyebrows, nose, lips, jawline, cheeks, ears, skin tone, facial hair, hairline, hairstyle, and hair color. Do not retain any facial feature from the original driver and do not combine image 2 with images 1, 3, or 4. Keep the image-2 identity stable in every frame, including profile views, head turns, open-mouth singing, hand movement, and motion blur. Apply the same exclusive identity preservation to images 1, 3, and 4. Preserve each person''s apparent age, gender presentation, natural body build, weight, height, shoulder width, and body proportions; do not make anyone thinner, heavier, taller, shorter, younger, or older. Maintain temporal consistency with no face morphing, identity drift, duplicate faces, or hybrid people. Preserve the source video''s car interior, camera, framing, lighting, timing, seat positions, gestures, movement, and lip movement. Preserve the exact clothing, colors, materials, and accessories shown in each corresponding reference image. If part of an outfit is not visible, extend that same outfit naturally without changing its style. Change only the four actors'' identities and reproduce their referenced clothing; do not change anything else.',
  '',
  1,
  true,
  'https://tg-miniapp-liart.vercel.app/assets/templates/rap-in-car-cover.jpg',
  'https://tg-miniapp-liart.vercel.app/assets/templates/rap-in-car-preview.mp4',
  'https://tg-miniapp-liart.vercel.app/assets/templates/rap-in-car-source.mp4',
  'genjutsu_motion_template',
  4,
  '["Человек слева спереди", "Человек справа спереди", "Человек слева сзади", "Человек справа сзади"]'::jsonb,
  '["480p", "720p", "1080p"]'::jsonb,
  'none',
  'genjutsu_motion',
  '16:9',
  20.077,
  '480p'
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  video_prompt = excluded.video_prompt,
  photo_prompt = excluded.photo_prompt,
  price_rub = excluded.price_rub,
  is_active = excluded.is_active,
  cover_url = excluded.cover_url,
  preview_video_url = excluded.preview_video_url,
  source_video_url = excluded.source_video_url,
  generation_mode = excluded.generation_mode,
  required_photo_count = excluded.required_photo_count,
  photo_rules = excluded.photo_rules,
  available_resolutions = excluded.available_resolutions,
  photo_model = excluded.photo_model,
  video_model = excluded.video_model,
  aspect_ratio = excluded.aspect_ratio,
  duration = excluded.duration,
  resolution = excluded.resolution;
