alter table public.templates
  add column if not exists description text,
  add column if not exists cover_url text,
  add column if not exists preview_video_url text,
  add column if not exists source_video_url text,
  add column if not exists generation_mode text not null default 'legacy',
  add column if not exists required_photo_count integer not null default 1,
  add column if not exists photo_rules jsonb not null default '[]'::jsonb,
  add column if not exists available_resolutions jsonb not null default '["720p"]'::jsonb;

alter table public.orders
  add column if not exists template_options jsonb not null default '{}'::jsonb;

insert into public.templates (
  slug,
  title,
  description,
  video_prompt,
  photo_prompt,
  price_rub,
  is_active,
  cover_url,
  preview_video_url,
  source_video_url,
  generation_mode,
  required_photo_count,
  photo_rules,
  available_resolutions,
  photo_model,
  video_model,
  aspect_ratio,
  duration,
  resolution
) values (
  'rap_in_car',
  'Рэп в машине',
  'Замените четырёх героев ролика своими фотографиями.',
  'Replace the four people in the source video with the four people from the reference images. Use this strict mapping in every frame: image 1 = front-left person (screen left foreground); image 2 = front-right person (screen right foreground); image 3 = rear-left person (screen left background); image 4 = rear-right person (screen right background). Never swap identities or positions. Preserve each referenced person''s exact recognizable identity, facial structure, eyes, nose, mouth, skin tone, hairstyle, hair color, apparent age, gender presentation, and natural body build. Keep their original body proportions, weight, shoulder width, and face shape; do not make anyone thinner, heavier, taller, shorter, younger, or older. Preserve the clothing, colors, materials, and accessories shown in each corresponding reference image. If part of an outfit is not visible, extend the same outfit naturally without changing its style. Keep faces and bodies consistent throughout the entire video without morphing or identity drift. Preserve the source video''s car interior, camera angle, framing, lighting, timing, movements, gestures, lip movement, and seat positions. Change only the identities and clothing of the four people according to the references.',
  '',
  1,
  true,
  'https://tg-miniapp-liart.vercel.app/assets/templates/rap-in-car-cover.jpg',
  'https://tg-miniapp-liart.vercel.app/assets/templates/rap-in-car-preview.mp4',
  'https://tg-miniapp-liart.vercel.app/assets/templates/rap-in-car-source.mp4',
  'genjutsu_motion_template',
  4,
  '["Человек слева спереди", "Человек справа спереди", "Человек слева сзади", "Человек справа сзади"]'::jsonb,
  '["480p", "720p", "1080p"]'::jsonb,
  'none',
  'genjutsu_motion',
  '16:9',
  20.077,
  '480p'
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  video_prompt = excluded.video_prompt,
  photo_prompt = excluded.photo_prompt,
  price_rub = excluded.price_rub,
  is_active = excluded.is_active,
  cover_url = excluded.cover_url,
  preview_video_url = excluded.preview_video_url,
  source_video_url = excluded.source_video_url,
  generation_mode = excluded.generation_mode,
  required_photo_count = excluded.required_photo_count,
  photo_rules = excluded.photo_rules,
  available_resolutions = excluded.available_resolutions,
  photo_model = excluded.photo_model,
  video_model = excluded.video_model,
  aspect_ratio = excluded.aspect_ratio,
  duration = excluded.duration,
  resolution = excluded.resolution;
