alter table public.templates
  add column if not exists description text,
  add column if not exists cover_url text,
  add column if not exists preview_video_url text,
  add column if not exists source_video_url text,
  add column if not exists generation_mode text not null default 'legacy',
  add column if not exists required_photo_count integer not null default 1,
  add column if not exists photo_rules jsonb not null default '[]'::jsonb,
  add column if not exists available_resolutions jsonb not null default '["720p"]'::jsonb;

insert into public.templates (
  slug,
  title,
  description,
  video_prompt,
  photo_prompt,
  price_rub,
  is_active,
  cover_url,
  preview_video_url,
  source_video_url,
  generation_mode,
  required_photo_count,
  photo_rules,
  available_resolutions,
  photo_model,
  video_model,
  aspect_ratio,
  duration,
  resolution
) values (
  'zombie_drama',
  'Зомби драма',
  'Станьте героями драматичной истории о любви и зомби.',
  'Edit the uploaded source video and replace only the two people. Keep everything else identical to the original: the same shots, cuts, timing, camera movement, lighting, locations, backgrounds, props, gun, wardrobe shapes, tear tracks, wind, sunset, color grade, film grain, framing, and performances. Keep it ultrarealistic live-action. No restyle, no new scenes, and no extra characters. Image 1 replaces the man in every shot. Lock the exact recognizable identity, face, hair, skin tone, age, height, body build, weight, and proportions from image 1. Use the same man in the dark house and in all golden-field memories. Map him precisely onto the original man''s head position, eye line, crying, aiming, lowering the gun, opening his arms, smiling, running, and kissing. Never redesign, blend, or distort his face or body. Image 2 replaces the woman in every shot and must remain the same exact recognizable woman throughout. In the dark-house scenes only, render the woman from image 2 in the original infected state while preserving her exact facial structure and identity: keep the milky eyes, dirty cracked skin, snarl, torn clothes, and feral twitch from the original performance. In the memory scenes only, render the same woman from image 2 healthy, with her exact natural face, hair, skin tone, age, height, body build, weight, and proportions, while lying in the grass, laughing in close-up, running through the field, and sitting at sunset. Do not blend image 1 and image 2. Do not mix either identity with the original actors. Do not put the healthy face on the infected body or the infected appearance on the healthy memory woman. Maintain stable facial identity and body proportions in every frame, including profiles, motion, crying, smiling, running, and kissing. Do not change the windows, kitchen shelves, grass, sky, camera path, or scene composition. Preserve photorealistic skin contact, wet tears, and natural head tracking to the original motion.',
  '',
  273,
  true,
  'https://tg-miniapp-liart.vercel.app/assets/templates/zombie-drama-cover.jpg',
  'https://tg-miniapp-liart.vercel.app/assets/templates/zombie-drama-preview.mp4',
  'https://tg-miniapp-liart.vercel.app/assets/templates/zombie-drama-source.mp4',
  'genjutsu_motion_template',
  2,
  '["Мужчина", "Девушка"]'::jsonb,
  '["480p", "720p", "1080p"]'::jsonb,
  'none',
  'genjutsu_motion',
  '16:9',
  24,
  '480p'
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  video_prompt = excluded.video_prompt,
  photo_prompt = excluded.photo_prompt,
  price_rub = excluded.price_rub,
  is_active = excluded.is_active,
  cover_url = excluded.cover_url,
  preview_video_url = excluded.preview_video_url,
  source_video_url = excluded.source_video_url,
  generation_mode = excluded.generation_mode,
  required_photo_count = excluded.required_photo_count,
  photo_rules = excluded.photo_rules,
  available_resolutions = excluded.available_resolutions,
  photo_model = excluded.photo_model,
  video_model = excluded.video_model,
  aspect_ratio = excluded.aspect_ratio,
  duration = excluded.duration,
  resolution = excluded.resolution;
